### ISSUE TITLE
[l10n_es_ticketbai] Campos TBAI cuando se crea la factura desde otro módulo

### ISSUE THREAD

**Issue by Bilbonet** [binovo/l10n-spain#1]
Cuando creamos una factura desde otro módulo como el de contratos por ejemplo.
El método **'create'** cuando **no es una rectificativa** no contempla los campos para el TBAI y no se rellenan.

Cuando se crea una factura desde otro módulo es común llamar al método **'_onchange_partner_id'** para obtener todos los campos extra de la factura que no se contemplan desde el modulo que está creando la factura.

No se si sería mejor modificar el método 'create', o heredar el '_onchange_partner_id' y que obtenga los valores de los campos antes de crear la factura.

Saludos.

**Comment by Bilbonet** [comment]
@ljsalvatierra-binovo has podido mirar algo de esto.

**Comment by ljsalvatierra-binovo** [comment]
@Bilbonet Disculpa no haber contestado antes. Estamos ahora mismo desbordados con el desarrollo para TPV, ¿podríais hacer un PR?
