### ISSUE TITLE
l10n_es_edi_verifactu

### ISSUE THREAD

**Issue by CrazyIFriT** [binovo/l10n-spain#4]
He probado el modulo de verifactu como sale en el video y bueno testeando me sale un error con todo el typescript del xml-gen (el contenido que sale es muy grande). No sé si me falta algo por hacer. Estoy probando en Odoo 16 

![image](https://github.com/user-attachments/assets/1ff60c1e-8a38-41d7-9fbe-87725146e1a0)

**Comment by CrazyIFriT** [comment]
Vale pongo respuesta, tiene que ser Node 18, en mi caso, 18.20.4  actualmente

**Comment by blaskurain** [comment]
No estoy seguro de entenderte: ¿entonces con la versión correcta te funciona o sigues viendo el mismo error?

**Comment by CrazyIFriT** [comment]
funciona, gracias.

**Comment by blaskurain** [comment]
Estupendo, lo damos entonces por cerrado, muchas gracias.
